### ISSUE TITLE
QR integration in thankyou e-mail

### ISSUE THREAD

**Issue by R0N7N** [Coernel82/SEPA-QR-for-Woocommerce#10]
For me the QR code in the email doesn't work / show up.
I tested with diferent clients and the code is always just a blank white square.

I think the way to solve this would be to add the QR code as attachment with "--boundary" to the email and "<img src=" to this attachment.

**Comment by Coernel82** [comment]
As with the update vom v. 1.0.0 to 1.0.1 the deprecated variable `order_total` has been repalced by `get_total()` which also effects the email please update to 1.0.1 and check again and tell me if this still is an issue.
Could you please write out the complete code? I think we talk about [line 88, right?](https://github.com/Coernel82/SEPA-QR-for-Woocommerce/blob/main/mxp-sepaqr/mxp-sepaqr.php#L88)

`echo '<p>' . THANKYOU_EMAIL . '<br> <img src="' . mxp_get_qrcode($order->get_total(), $order->get_id()) . '"></p>';`

For me the QR shows up in both emails in 1.0.0 and 1.0.1

**Comment by R0N7N** [comment]
HI, for me the QR was not working in 1.0.0
But now I changeed the mxp_email_after_order_table to the 1.0.1 version and now it works fine.
Thank you for your help!

When I have time I will add the other 1.0.1 updates to my installation

**Comment by R0N7N** [comment]
Ok I was to fast with my assumption.
It works on Apple Mail Client, Hotmail Web View, 
But not on Gmail App and Windows Mail program.
I think thats because of the deprecated method of integrating images into the email

**Comment by Coernel82** [comment]
Have a look in the code from https://github.com/Coernel82/SEPA-QR-for-Woocommerce/blob/42a9b82437ee9d9f8c0d7400dd2790abbd3b1b2c/mxp-sepaqr/mxp-sepaqr.php#L84-L86 - there are ideas in the comment how to solve this. As said in the description there are very limited resources for this plugin and we might have to live with this.
Have a look at https://github.com/Coernel82/SEPA-QR-for-Woocommerce/blob/42a9b82437ee9d9f8c0d7400dd2790abbd3b1b2c/mxp-sepaqr/mxp-sepaqr.php#L46 - I added the sad text that some mail clients won't show the image.

**Comment by Mathijsvdbeek** [comment]
I updated my code to
`mxp-sepaqr/mxp-sepaqr.php` Line 87
if ( !empty($order->get_total()) && (float)$order->get_total() > 0  && $order->get_payment_method() == 'bacs'  && ('on-hold' == $order->status || 'pending' == $order->status))

Now only in the pending emails and on hold status emails (if you got these) the QR code will be added. Works fine on my site.

**Comment by Coernel82** [comment]
> I updated my code to

I integrated it into the code
