### ISSUE TITLE
Not recognized code SEPA

### ISSUE THREAD

**Issue by vortexfoto** [Coernel82/SEPA-QR-for-Woocommerce#11]
Everything works, but if i scan the qr code with reader i get all info but not in iso type, luke ISO requirement is that price is in 7 digit format so 1.01 eur must be 0000101 - like that and some other stuff too

**Comment by Coernel82** [comment]
Your information is wrong:
http://www.europeanpaymentscouncil.eu/index.cfm/sepa-credit-transfer/sepa-credit-transfer-sct/
