### ISSUE TITLE
Will this work with WooCommerce builtin Bacs?

### ISSUE THREAD

**Issue by uhlhosting** [Coernel82/SEPA-QR-for-Woocommerce#12]
Hi,

Will this pull values from WooCommerce Bacs payment method?

**Comment by uhlhosting** [comment]
Also it seems to be blocked to EUR currency, would be great if it could read the current currency in shop.

**Comment by Coernel82** [comment]
I am not sure if I understand what you mean however I try to answer:

The plugin uses the IBAN from the Bacs settings. As far as I know it uses the first one in case you entered multiple values. The plugin also has a fallback: You can hardcode your IBAN in the sourcecode.

And yes, it uses EUR. Everything else doesn't make sense, does it? It is SEPA where E stands for European. So there will no modification been made in this regard.

Feel free to re-open the issue if your question has not been answered.

**Comment by uhlhosting** [comment]
I was trying to adapt this to local bank payments, since IBAN contains always the local bank account, and yes now I see this is strictly for SEPA payments. Will see if I can manage to adapt it to work with local payments .
