### ISSUE TITLE
Thank you email QR code also in final email

### ISSUE THREAD

**Issue by Mathijsvdbeek** [Coernel82/SEPA-QR-for-Woocommerce#16]
First thank you for this plugin. It works lovely. 

I noticed that the email waiting for payment and also the final email payment received contain the QR code.

In the code I see woocommerce_email_after_order_table 
Is it possible to hook this only to the waiting for payment email? And how can this be done?

Kind regards

**Comment by Mathijsvdbeek** [comment]
I think I resolved it. By adding && ('on-hold' == $order->status || 'pending' == $order->status)) in the code

	if ( !empty($order->get_total()) && (float)$order->get_total() > 0  && $order->get_payment_method() == 'bacs'  && ('on-hold' == $order->status || 'pending' == $order->status))

**Comment by Coernel82** [comment]
Can you test it further and make a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)?

Also if you have some idea about programming you could have a look at #10 as this would help many people!
