### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by petermorlion** [Coernel82/SEPA-QR-for-Woocommerce#19]
This plugin is exactly what I need, yet I work in a Dutch-speaking environment. I see the pieces of text are currently hard-coded English. I believe it would improve the plugin if localization were added. I'm willing to help out if you want. I can create a PR if that's the way you work (don't know if GitHub is your master or the Subversion repository you got from WordPress).

**Comment by Coernel82** [comment]
Hello @petermorlion to my mind I do have localization: https://translate.wordpress.org/projects/wp-plugins/mxp-sepa-qr-code-addon-for-woocommerce/

If there really are hardcoded strings left you are welcome to open a PR here on GitHub!

The thing is the following: There is an overload of plugins and Woocommerce is badly organzied - if you transate on that page it probably will never be released from the translation team as they have translations for years. But I guess there are plugins like loco translate where you can override that, right?

**Comment by petermorlion** [comment]
Yeah, sorry, I can't remember where I saw this, and looking at the code, I don't see any issue. My apologies.
