### ISSUE TITLE
PHP Warning:  Use of undefined constant USE_TRANSIENTS

### ISSUE THREAD

**Issue by designboxcom** [Coernel82/SEPA-QR-for-Woocommerce#5]
Hello,

The plugin actually throws the following PHP Warning:
`[18-Jan-2022 11:33:47 UTC] PHP Warning:  Use of undefined constant USE_TRANSIENTS - assumed 'USE_TRANSIENTS' (this will throw an Error in a future version of PHP) in /home/xxxxxxxx/wp-content/plugins/mxp-sepaqr/mxp-sepaqr.php on line 195
`

I am using PHP 7.4 on my dev box.

**Comment by Coernel82** [comment]
Please check if you used the version here from this repository. Sorry - we did not update the version number.
In the Code line 195 is `  return $base64;` and nothing about the transients.

After that in 202 and 203:

` if (defined(USE_TRANSIENTS)) { 
		  return get_transient( $transient );`

From my understanding your error gets intercepted here.

So please check and let me know.

**Comment by designboxcom** [comment]
Hi, thank you very much. I did replace with the current version but still the same error message is poping into the logs. 
`[24-Jan-2022 10:03:35 UTC] PHP Warning:  Use of undefined constant USE_TRANSIENTS - assumed 'USE_TRANSIENTS' (this will throw an Error in a future version of PHP) in /home/xxxxxxxx/wp-content/plugins/mxp-sepaqr/mxp-sepaqr.php on line 202
`

**Comment by designzwang** [comment]
Just a stupid typo  which is easily fixed like the error message suggests.  While the warning can be ignored, of course it should be fixed to run without warnings. @Coernel82 : There is a pull request ready for merging.

**Comment by Coernel82** [comment]
Updated and closed.
