### ISSUE TITLE
CRITICAL Cannot declare class Bezahlcode, because the name is already in use

### ISSUE THREAD

**Issue by hrvoje05** [Coernel82/SEPA-QR-for-Woocommerce#7]
The Qr code was displayed in my e-mail, but after the purchase it did not go to the thankyou page, it just remained at the checkout, without any sign. This error was also printed in error.log:

CRITICAL Cannot declare class Bezahlcode, because the name is already in use.

I changed this piece of code from mxp-sepaqr.php to line 187 from require to require_once and everything working good now.

require_once(dirname(__FILE__) . "/vendor/bezahlcode/bezahlcode.class.php");

Cheers.

**Comment by Coernel82** [comment]
Thank you!
Fixed.
